# Generated by Django 3.1.2 on 2020-11-25 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('npm', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=31)),
                ('org_code', models.CharField(max_length=11)),
                ('faculty', models.CharField(max_length=63)),
                ('study_program', models.CharField(max_length=63)),
                ('educational_program', models.CharField(max_length=63)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
