<<<<<<< HEAD
# Generated by Django 3.1.2 on 2021-11-08 02:55
=======
# Generated by Django 3.1.2 on 2021-11-05 14:06
>>>>>>> 905075b1efb9f743919d4ed6748522e9dc0a8e0d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
<<<<<<< HEAD
            field=models.ManyToManyField(blank=True, related_name='courses', to='main.Tag'),
=======
            field=models.ManyToManyField(blank=True, to='main.Tag'),
>>>>>>> 905075b1efb9f743919d4ed6748522e9dc0a8e0d
        ),
    ]
