# Generated by Django 3.1.2 on 2022-07-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
