# Generated by Django 4.0.6 on 2022-07-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_beneficial',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_fit_to_credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_fit_to_study_book',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_recommended',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_understandable',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
