# Generated by Django 4.0.6 on 2022-07-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review_rating_beneficial_review_rating_fit_to_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
