# Generated by Django 4.0.6 on 2022-07-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_likes_count_review_rating_beneficial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
