# Generated by Django 4.0.6 on 2022-07-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating_beneficial',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_fit_to_credit',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_fit_to_study_book',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_recommended',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_understandable',
            field=models.FloatField(default=0, null=True),
        ),
    ]
