# Generated by Django 3.1.2 on 2024-07-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_review_rating_beneficial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCumulativeGPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumulative_gpa', models.FloatField(default=0)),
                ('total_gpa', models.FloatField(default=0)),
                ('total_sks', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserGPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_semester', models.PositiveSmallIntegerField(editable=False)),
                ('total_sks', models.PositiveIntegerField()),
                ('semester_gpa', models.FloatField()),
                ('userCumulativeGPA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usercumulativegpa')),
            ],
        ),
    ]
