# Generated by Django 3.1.2 on 2024-07-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20240712_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='usergpa',
            name='given_semester',
            field=models.CharField(max_length=20),
        ),
    ]
