# Generated by Django 3.1.2 on 2024-07-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240713_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usergpa')),
            ],
        ),
        migrations.DeleteModel(
            name='SemesterCalculator',
        ),
    ]
