# Generated by Django 3.1.2 on 2024-07-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20240714_1437'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursesemester',
            constraint=models.UniqueConstraint(fields=('semester', 'course'), name='unique_semester_course'),
        ),
    ]
