# Generated by Django 3.1.2 on 2024-07-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20240716_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergpa',
            name='semester_gpa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usergpa',
            name='total_sks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
