# Generated by Django 3.1.2 on 2024-07-17 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20240716_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesemester',
            name='calculator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.calculator'),
        ),
    ]
