# Generated by Django 3.1.2 on 2024-07-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_coursesemester_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergpa',
            name='semester_mutu',
            field=models.FloatField(default=0),
        ),
    ]
