# Generated by Django 3.1.2 on 2024-08-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
