# Generated by Django 3.1.2 on 2024-08-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_question_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='verification_status',
            field=models.TextField(choices=[('Menunggu Verifikasi', 'Waiting'), ('Terverifikasi', 'Approved')], default='Menunggu Verifikasi'),
        ),
    ]
