# Generated by Django 3.1.2 on 2024-08-09 00:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_question_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 0, 24, 51, 49643, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 0, 24, 51, 49654, tzinfo=utc)),
        ),
    ]
