# Generated by Django 3.1.2 on 2024-08-18 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20240817_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_anonym', models.IntegerField()),
                ('attachment', models.CharField(max_length=120, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('verification_status', models.TextField(choices=[('Menunggu Verifikasi', 'Waiting'), ('Terverifikasi', 'Approved')], default='Menunggu Verifikasi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
