# Generated by Django 3.1.2 on 2024-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attachment',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='attachment',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
